kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
networking:
  disableDefaultCNI: false
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30101
    hostPort: 30101
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
      - hostPath: src/
        containerPath: /var/www/html