apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-rbac-policies
spec:
  validationFailureAction: enforce
  rules:
  - name: validate-rbac-policies
    match:
      any:
      - resources:
          kinds:
            - Role
            - ClusterRole
    validate:
      message: "Do not implement dangerous permissions"
      pattern:
        metadata:
          rules:
            apiGroups: [""]
            resources: ["*"]
            verbs: ["*"]