apiVersion: apps/v1
kind: Deployment
metadata:
 name: myservicepod7
 namespace: vault
 labels:
  app: servicepod
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: servicepod
 template:
  metadata:
    labels:
     app: servicepod
    annotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'web'
      vault.hashicorp.com/agent-inject-secret-data-config.txt: 'database/data/config'
  spec:
   serviceAccountName: utk
   automountServiceAccountToken: true
   volumes:
   - name: hostvolume
     hostPath:
      path: /var/www/html
   containers:
   - name: php
     image: php:7.2-apache
     command: ["/bin/sh", "-c"]
     args: ["service apache2 start; sleep infinity"]
     workingDir: /var/www/html
     ports:
      - name: serviceport
        containerPort: 80 
     volumeMounts: 
      - name: hostvolume
        mountPath: /var/www/html

---

apiVersion: v1
kind: ServiceAccount
metadata: 
 name: utk
 namespace: vault
automountServiceAccountToken: true