apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: vault
 labels:
  app: servicepod
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: servicepod
 template:
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'vaultread'
      vault.hashicorp.com/agent-inject-secret-internal-config.txt: 'database/data/internal/config'
      vault.hashicorp.com/agent-inject-template-database-config: |
        {{ with secret "database/data/internal/config" -}}
        export password={{ .Data.password }}
        {{- end }}

      vault.hashicorp.com/agent-inject-command-database-config: /bin/sh -c "source /vault/secrets/internal-config"
    labels:
     app: servicepod
  spec:
   serviceAccountName: utk
   volumes:
   - name: hostvolume
     hostPath:
      path: /var/www/html
   containers:
   - name: php
     image: php:7.2-apache
     command: ["/bin/sh", "-c"]
     args: ["service apache2 start ; sleep infinity"]
     workingDir: /var/www/html
     ports:
      - name: serviceport
        containerPort: 80 
     volumeMounts: 
      - name: hostvolume
        mountPath: /var/www/html

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: orgchart
#   labels:
#     app: orgchart
# spec:
#   selector:
#     matchLabels:
#       app: orgchart
#   replicas: 1
#   template:
#     metadata:
#       annotations:
#         vault.hashicorp.com/agent-inject: 'true'
#         vault.hashicorp.com/role: 'internal-app'
#         vault.hashicorp.com/agent-inject-secret-internal-config.txt: 'database/data/internal/config'
#       labels:
#         app: orgchart
#     spec:
#       serviceAccountName: internal-app
#       containers:
#         - name: orgchart
#           image: jweissig/app:0.0.1
