apiVersion: apps/v1
kind: Deployment
metadata:
 name: myservicepod7
 labels:
  app: servicepod
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: servicepod
 template:
  metadata:
    labels:
     app: servicepod
  spec:
   serviceAccountName: utk
   automountServiceAccountToken: false
   volumes:
   - name: hostvolume
     hostPath:
      path: /var/www/html
   containers:
   - name: php
     image: php:7.2-apache
     command: ["/bin/sh", "-c"]
     args: ["service apache2 start; sleep infinity"]
     workingDir: /var/www/html
     ports:
      - name: serviceport
        containerPort: 80 
     volumeMounts: 
      - name: hostvolume
        mountPath: /var/www/html
        
---
apiVersion: v1
kind: Service
metadata:
 name: myservices
spec: 
 type: NodePort
 selector:
  app: servicepod
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
   nodePort: 30101

---
apiVersion: v1
kind: ServiceAccount
metadata: 
 name: utk
 namespace: default
automountServiceAccountToken: true